#!/bin/sh
# Unlock OPAL encrypted drives connected to the system

# Copyright (C) 2016  Joakim Nohlgård
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
SUCCESS=0
# Keep trying until one password works
while [ $SUCCESS -eq 0 ]; do
read -r -s -p 'Enter OPAL password: ' pass
echo
# Try to unlock all drives
for d in /dev/sd? /dev/nvme?n? /dev/nvme??n?; do
sedutil-cli --setLockingRange 0 rw "$pass" "$d"
if [ $? -eq 0 ]; then
SUCCESS=1
else
continue
fi
# Unhide partitions
sedutil-cli --setMBRDone on "$pass" "$d"
# Re-read partition tables in order to be able to mount the real partitions
hdparm -z "$d"
done
done
